name: Create Gentoo image

on:
  workflow_dispatch:

env:
  STAGE3_VERSION: 20240602T164858Z
  PORTAGE_VERSION: 20240607

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set current Date Time as VERSION
        shell: bash
        run: echo "VERSION=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Download stage3
        run: wget -q https://distfiles.gentoo.org/releases/amd64/autobuilds/${{ env.STAGE3_VERSION }}/stage3-amd64-desktop-systemd-${{ env.STAGE3_VERSION }}.tar.xz

      - name: Download portage
        run: wget -q https://distfiles.gentoo.org/snapshots/gentoo-${{ env.PORTAGE_VERSION }}.tar.xz

      - name: Install dependencies
        run: |
          sudo mkdir gentoo
          sudo tar --numeric-owner --strip-components=1 -xpf stage3-amd64-desktop-systemd-${{ env.STAGE3_VERSION }}.tar.xz -C gentoo
          sudo mkdir -p gentoo/var/db/repos/gentoo
          sudo tar --numeric-owner --strip-components=1 -xpf gentoo-${{ env.PORTAGE_VERSION }}.tar.xz -C gentoo/var/db/repos/gentoo

          sudo cp /etc/resolv.conf gentoo/etc

          sudo mount -t proc /proc gentoo/proc/
          sudo mount -t sysfs /sys gentoo/sys/
          sudo mount --rbind /dev gentoo/dev/
          sudo mount --rbind /run gentoo/run/

          sudo chroot gentoo/ << "EOT"
          echo "LABEL=gentoo / ext4 rw,relatime,data=ordered 0 1" >> /etc/fstab

          sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
          sed -i 's/#en_GB.UTF-8 UTF-8/en_GB.UTF-8 UTF-8/g' /etc/locale.gen
          locale-gen

          echo "LANG=en_US.UTF-8" >> /etc/locale.conf
          echo "KEYMAP=us" >> /etc/vconsole.conf
          echo "playstation" >> /etc/hostname
          ln -sf /usr/share/zoneinfo/US/Pacific /etc/localetime

          mkdir -p /lib/firmware/edid

          useradd -m pi -G pi
          passwd pi
          raspberry
          raspberry

          emerge vim sudo

          echo '%wheel ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers
          echo 'Defaults lecture="never"' >> /etc/sudoers

          su pi
          cd ~/
          touch ~/.sudo_as_admin_successful

          exit
          EOT

          sudo umount -l gentoo/proc/
          sudo umount -l gentoo/sys/
          sudo umount -l gentoo/dev/
          sudo umount -l gentoo/run/

          sudo tar -czpf gentoo-${{ env.PORTAGE_VERSION }}.tar.xz --one-file-system -C gentoo .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gentoo-${{ env.PORTAGE_VERSION }}
          path: gentoo-${{ env.PORTAGE_VERSION }}.tar.xz
