name: Create Gentoo image

on:
  workflow_dispatch:

env:
  STAGE3_VERSION: 20240602T164858Z
  PORTAGE_VERSION: 20240607

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set current Date Time as VERSION
        shell: bash
        run: echo "VERSION=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Download stage3
        run: wget -q https://distfiles.gentoo.org/releases/amd64/autobuilds/${{ env.STAGE3_VERSION }}/stage3-amd64-desktop-systemd-${{ env.STAGE3_VERSION }}.tar.xz

      - name: Download portage
        run: wget -q https://distfiles.gentoo.org/snapshots/gentoo-${{ env.PORTAGE_VERSION }}.tar.xz

      - name: Install dependencies
        run: |
          sudo mkdir gentoo
          sudo tar --numeric-owner --strip-components=1 -xpf stage3-amd64-desktop-systemd-${{ env.STAGE3_VERSION }}.tar.xz -C gentoo
          sudo mkdir -p gentoo/var/db/repos/gentoo
          sudo tar --numeric-owner --strip-components=1 -xpf gentoo-${{ env.PORTAGE_VERSION }}.tar.xz -C gentoo/var/db/repos/gentoo

          sudo cp /etc/resolv.conf gentoo/etc

          sudo mount -t proc /proc gentoo/proc/
          sudo mount -t sysfs /sys gentoo/sys/
          sudo mount --rbind /dev gentoo/dev/
          sudo mount --rbind /run gentoo/run/

          sudo chroot gentoo/ << "EOT"
          echo "LABEL=gentoo / ext4 rw,relatime,data=ordered 0 1" >> /etc/fstab

          sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
          sed -i 's/#en_GB.UTF-8 UTF-8/en_GB.UTF-8 UTF-8/g' /etc/locale.gen
          locale-gen

          echo "LANG=en_US.UTF-8" >> /etc/locale.conf
          echo "KEYMAP=us" >> /etc/vconsole.conf
          echo "playstation" >> /etc/hostname
          ln -sf /usr/share/zoneinfo/US/Pacific /etc/localetime

          cat << EOF > /etc/portage/make.conf
          COMMON_FLAGS="-march=x86-64-v2 -mtune=btver2 -flto=4 -O2 -pipe"
          CFLAGS="\${COMMON_FLAGS}"
          CXXFLAGS="\${COMMON_FLAGS}"
          FCFLAGS="\${COMMON_FLAGS}"
          FFLAGS="\${COMMON_FLAGS}"
          BINPKG_FORMAT="gpkg"
          BINPKG_COMPRESS="lz4"                                                                                            EMERGE_DEFAULT_OPTS="-av"
          EMERGE_DEFAULT_OPTS="\${EMERGE_DEFAULT_OPTS} --usepkg-exclude 'sys-kernel/gentoo-sources virtual/*'"
          MAKEOPTS="-j4 -l4"
          LC_MESSAGES=C.utf8
          LINGUAS="en"
          L10N="en en-US"
          PYTHON_TARGETS="python3_12"
          PYTHON_SINGLE_TARGET="python3_12"
          LUA_TARGETS="lua5-3 lua5-4"
          LUA_SINGLE_TARGET="lua5-3"
          RUBY_TARGETS="ruby31 ruby32"
          PHP_TARGETS="php8-1"
          LLVM_TARGETS="AMDGPU"
          VIDEO_CARDS="amdgpu radeon radeonsi lavapipe"
          ACCEPT_KEYWORDS="~amd64"
          ACCEPT_LICENSE="*"
          INPUT_DEVICES="libinput keyboard mouse evdev joystick"
          USE="X abi_x86_64 abi_x86_32 lto -systemd elogind dbus ibus policykit pulseaudio pipewire \
            -gstreamer wayland -gnome -kde -xinerama -samba -xscreensaver \
            networkmanager nftables openvpn lm_sensors lm-sensors hddtemp bluetooth \
            highlight vim-syntax hscolour appindicator startup-notification libnotify \
            joystick touchpad gamepad alsa screencast dvd user-session notify \
            vdpau dri3 vulkan opengl gles gles1 gles3 gles2 d3d9 osmesa opencl dhcpcd vala \
            zip xa sdl2 egl sdl bluray bdplus aacs nfs v4l x264 x265 \
            drm vaapi ffmpeg vulkan-overlay evdev udev qml \
            -jack mda-lv2 zamaudio portaudio ladspa vst sndio tremor discid cdio \
            flac aac dts mp3 mp4 mikmod modplug theora xvid opus midi wildmidi \
            timidity libsamplerate speex ogg vorbis cdda cddb id3tag mad audiofile \
            svg png apng webp heif jpeg -tiff gif raw exif openexr \
            spell fontconfig corefonts truetype freetype ttf tahoma pdf"
          GENTOO_MIRRORS="http://ftp.free.fr/mirrors/ftp.gentoo.org/ http://mirrors.soeasyto.com/distfiles.gentoo.org/ http://gentoo.mirrors.ovh.net/gentoo-distfiles/"
          EOF

          cat << EOF > /etc/portage/repos.conf/gentoo.conf
          sync-type = rsync
          sync-uri = rsync://rsync.gentoo.org/gentoo-portage
          auto-sync = no
          priority = 25
          EOF

          emerge --nodeps vim
          emerge git sudo

          git clone https://github.com/Dr4kk3N/ps4-overlay.git /var/db/repos/ps4-overlay

          cat << EOF > /etc/portage/repos.conf/ps4-overlay.conf
          location = /var/db/repos/ps4-overlay
          sync-type = git
          sync-uri = https://github.com/Dr4kk3N/ps4-overlay.git
          priority = 50
          auto-sync = yes
          EOF

          cat << EOF > /etc/portage/package.mask/gentoo.mask
          x11-libs/libdrm::gentoo
          x11-drivers/xf86-video-amdgpu::gentoo
          media-libs/mesa::gentoo
          EOF

          emerge x11-libs/libdrm::ps4-overlay \
                 x11-drivers/xf86-video-amdgpu::ps4-overlay \
                 media-libs/mesa::ps4-overlay

          mkdir -p /lib/firmware/edid

          useradd -m pi -G pi
          passwd pi
          raspberry
          raspberry

          echo '%wheel ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers
          echo 'Defaults lecture="never"' >> /etc/sudoers

          su pi
          cd ~/
          touch ~/.sudo_as_admin_successful

          exit
          EOT

          sudo umount -l gentoo/proc/
          sudo umount -l gentoo/sys/
          sudo umount -l gentoo/dev/
          sudo umount -l gentoo/run/

          sudo tar -czpf gentoo-${{ env.PORTAGE_VERSION }}.tar.xz --one-file-system -C gentoo .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gentoo-${{ env.PORTAGE_VERSION }}
          path: gentoo-${{ env.PORTAGE_VERSION }}.tar.xz
